package middleware.service;

import java.util.List;

/**
 * Service interface for embedding generation.
 * Provides abstraction for different embedding providers.
 */
public interface EmbeddingService {
    
    /**
     * Generate embeddings for the given text.
     * 
     * @param text The text to embed
     * @return List of embedding values as floats
     */
    List<Float> generateEmbedding(String text);
    
    /**
     * Generate embeddings for multiple texts.
     * 
     * @param texts List of texts to embed
     * @return List of embedding lists
     */
    List<List<Float>> generateEmbeddings(List<String> texts);
    
    /**
     * Get the dimensionality of embeddings generated by this service.
     * 
     * @return The embedding dimension
     */
    int getEmbeddingDimension();
    
    /**
     * Check if the embedding service is healthy and available.
     * 
     * @return true if the service is healthy
     */
    boolean isHealthy();
    
    /**
     * Get the model name used by this embedding service.
     * 
     * @return The model name
     */
    String getModelName();
}
