spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  data:
    redis:
      host: localhost
      port: 6379
  
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

# Test settings
knowledge:
  embeddings:
    url: http://localhost:8081/embeddings
    model: sentence-transformers/all-MiniLM-L6-v2
  
  llm:
    provider: mock
    model: gpt-3.5-turbo
  
  blob-storage:
    type: local
    local:
      path: ./data/test-blobs
  
  vector-store:
    type: mock

logging:
  level:
    middleware: DEBUG
    org.springframework.test: DEBUG
